Implemented connect wallet and Jupiter swap Module
solana-fm/solana pull request #1
Opened 2022-07-21 18:47 UTC by Yash621

#### Problem
This PR is with respect to integration of jupiter swap module and connect wallet functionality in the solana explorer.

#### Summary of Changes
- Integrating Jupiter swap module (Functionality and UI)
- integrating connect wallet functionality

Fixes #
- used jupiter APIs for implementing swap of different tokens
- used solana-wallet-adapter for implementing wallet connectivity

Below is attached a visual representation of the jupiter swap module for reference

![Screenshot 2022-07-22 001526](https://user-images.githubusercontent.com/58719389/180291160-5b57ed61-6a57-4559-9332-b9be89a3386f.png)

2022-08-01 12:48 UTC, BingHuang-Chin commented
Please help us to update this branch with `nextjs-migration`

2022-08-02 12:55 UTC, Yash621 commented on explorer/src/components/JupiterSwapModal.tsx
> +	const [outputToken, setOutputToken] = useState<any>({});
sure, will add

2022-08-02 17:54 UTC, Yash621 commented on explorer/src/components/JupiterSwapModal.tsx
> +	const [outputToken, setOutputToken] = useState<any>({});
@lekekbot added the types

2022-08-17 07:57 UTC, gabrielkhh requested changes
Look through all the comments I have written.
IMPORTANT NOTE: All of the comments that were given are **not exhaustive**. This means that I might've missed out on some code snippets so please look through the files changed again and make sure to implement good react coding practices

2022-08-17 07:57 UTC, gabrielkhh commented on explorer/src/components/JupiterApp.tsx
> +      <JupiterProvider
We should not put providers in the components folder, it should be in the providers folder. Please modify

2022-08-17 07:57 UTC, gabrielkhh commented on explorer/pages/_app.tsx
> +		<JupiterContext>
Looks like this JupiterContext component is wrapping the Wallet Adapter (Wallet Provider) and the Jupiter Provider. Please separate them out into individual Providers to make it clear to find the Wallet Adapter and also to place them all within the Providers folder.

Please also initialise them in the ```ExplorerApp``` functional component within the ```_app.tsx``` file.. That's where all the providers are initialised.

2022-08-17 07:57 UTC, gabrielkhh commented on explorer/pages/_app.tsx
> +		<JupiterContext>
Can we also make sure that these Providers are named as per the convention of <[SomeName]Provider>? This is to ensure that all Provider components end with the word "Provider"

2022-08-17 07:57 UTC, gabrielkhh commented on explorer/pages/_app.tsx
> +		<JupiterContext>
For reference, look at the attached screenshot, this is the return statement for the ExplorerApp functional component. All Providers should be initialised over there.
<img width="724" alt="image" src="https://user-images.githubusercontent.com/20179273/185045986-29e837e7-a43a-46b3-af20-466634716a9e.png">

2022-08-17 07:57 UTC, gabrielkhh commented on explorer/src/components/JupiterApp.tsx
> +    }
Unnecessary code, we can just use the ```url``` attribute from the ```useCluster``` hook. Just destructure the "url" attribute as such
```const { cluster, customUrl, url } = useCluster();``` at line 9.

2022-08-17 07:57 UTC, gabrielkhh commented on explorer/src/components/Navbar.tsx
>    // TODO: use `collapsing` to animate collapsible navbar
Is this still pending TODO?

2022-08-17 07:57 UTC, gabrielkhh commented on explorer/src/components/JupiterSwapModal.tsx
> +    const currentClusterUrl = clusterUrl(cluster, customUrl);
Unused and unnecessary code, destructure the url from the ```useCluster``` hook if the url of the cluster is needed.

2022-08-17 07:57 UTC, gabrielkhh commented on explorer/src/components/JupiterSwapModal.tsx
> +    }
unnecessary code, same as the above.

2022-08-17 07:57 UTC, gabrielkhh commented on explorer/src/components/JupiterSwapModal.tsx
> +				const info = await connection.getParsedTokenAccountsByOwner(wallet.publicKey, {
Not necessary to retrieve Token Accounts by owner in this way, there is already a Provider method that you can use to getTokenAccountsByOwner. Look for ```useFetchAccountOwnedTokens``` hook.

2022-08-17 07:57 UTC, gabrielkhh commented on explorer/src/components/JupiterSwapModal.tsx
> +	const setTokenValues = async (token: any, type?: string) => {
Could we refrain from using "set[SomeName]" as function names as those are typically used in the setState function names for the various ```useState``` variables.

2022-08-17 07:57 UTC, gabrielkhh commented on explorer/src/components/JupiterSwapModal.tsx
> +	const setWalletBalance = async (tokenAddress: string, type: string) => {
Could we refrain from using "set[SomeName]" as function names as those are typically used in the setState function names for the various ```useState``` variables.

2022-08-17 07:57 UTC, gabrielkhh commented on explorer/src/components/JupiterSwapModal.tsx
> +	}
Potentially unnecessary as it just does one thing when TokenSearchChanges, as such can just call it inline.

2022-08-17 07:57 UTC, gabrielkhh commented on explorer/src/components/JupiterSwapModal.tsx
> +	const onClickSlippageOptionBtn = (selectedIdx: number) => {
Potentially unnecessary, as it is just one expression, can call it inline in the component onChange

2022-08-17 07:57 UTC, gabrielkhh commented on explorer/src/components/JupiterSwapModal.tsx
> +	const onAggregatorSearchChange = (value: string) => {
Potentially unnecessary, as it is just one expression, can call it inline in the component onChange

2022-08-17 07:57 UTC, gabrielkhh commented on explorer/src/components/JupiterSwapModal.tsx
> +			const info = await connection.getParsedTokenAccountsByOwner(publicKey, {
use the hooks provided by the TokenProvider as mentioned above, Look for ```useFetchAccountOwnedTokens``` hook.

2022-08-17 07:57 UTC, gabrielkhh commented on explorer/src/components/JupiterSwapModal.tsx
> +		fetch(TOKEN_LIST_URL["mainnet-beta"])
Allow token list for users to select to be dynamic (based on their current network)

2022-08-17 07:57 UTC, gabrielkhh commented on explorer/src/components/JupiterSwapModal.tsx
> +	}
Could we refrain from using "set[SomeName]" as function names as those are typically used in the setState function names for the various ```useState``` variables

2022-08-17 07:57 UTC, gabrielkhh commented on explorer/src/components/JupiterSwapModal.tsx
> +	}
Wrapping this in a useMemo would be preferred as it ensures that the code does not re run when the same tokenAddress is passed in again and also to ensure that the reference to the allTokens state is updated.

```suggestion
	const getTokenSymbol = useMemo((tokenAddress: String) => {
	        const tokenObj = allTokens.filter(token => token.address === tokenAddress)
	        return tokenObj.length > 0 ? tokenObj[0].symbol : null
	}, [allTokens])
```

2022-08-17 07:57 UTC, gabrielkhh commented on explorer/src/components/JupiterSwapModal.tsx
> +	const fetchSwapPath = (route: any) => {
Is it possible to see if there's a type for the route?

2022-08-17 07:57 UTC, gabrielkhh commented on explorer/src/components/JupiterSwapModal.tsx
> +		const path: any[] = [];
Is it possible to see if there's a type for the path?

2022-08-17 07:57 UTC, gabrielkhh commented on explorer/src/components/JupiterSwapModal.tsx
> +		route.marketInfos.forEach((item: any) => {
Same as the above

2022-08-17 07:57 UTC, gabrielkhh commented on explorer/src/components/JupiterSwapModal.tsx
> +
- Need clarification on the functionality of this function, but some thoughts immediately when seeing this is that, when watching variables that are part of useState, good to use useMemo or useEffect to ensure that the latest variable is being read.
- Also as mentioned somewhere above, please refrain from naming your custom function as set[SomeName], as it is misleading and might conflict with the setState functions for the various useStates in this file.
- Also, it appears that this function is setting the state of another variable when the inputToken and outputToken variable changes, perhaps a useEffect might be more suitable for this functionality? (need clarification on the functionality of this function)

2022-08-17 07:57 UTC, gabrielkhh commented on explorer/src/components/JupiterSwapModal.tsx
> +					}
Need clarification on the functionality of this function

2022-08-17 07:57 UTC, gabrielkhh commented on explorer/src/components/JupiterSwapModal.tsx
> +			const balance = info.value[0].account.data.parsed.info.tokenAmount.uiAmount;
<img width="963" alt="image" src="https://user-images.githubusercontent.com/20179273/185062756-9ddf5ad3-d58a-47d7-a5a5-9bb014ad65a6.png">

2022-08-17 07:57 UTC, gabrielkhh commented on explorer/src/components/JupiterSwapModal.tsx
> +			const balance = info.value[0].account.data.parsed.info.tokenAmount.uiAmount;
Seems to have an issue

2022-08-17 07:57 UTC, gabrielkhh commented on explorer/src/components/JupiterSwapModal.tsx
> +					) : null}
One neat way to do this is to use && operator.
```suggestion
					{showAggregatorSearch && (
						<AggregatorSearchModal
							aggregatorOptions={aggregatorOptions}
							setAggregator={setAggregator}
							aggregatorSearch={aggregatorSearch}
							onAggregatorSearchChange={onAggregatorSearchChange}
							setShowAggregatorSearch={setShowAggregatorSearch}
						/>
					)}
```

2022-08-17 07:57 UTC, gabrielkhh commented on explorer/src/providers/jupiter-context.tsx
> +            <WalletProvider wallets={wallets} autoConnect>
Separate the Wallet Adapter Provider from the Jupiter Provider and put the Wallet Adapter in another file with its own name. This is to make it less confusing lest we need to find the Wallet Provider

2023-02-28 08:03 UTC, closed without merging